## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  security:
    allowInsecureImages: true

## @section Common parameters
##

## @param clusterDomain Kubernetes cluster domain name
##
clusterDomain: ${CLUSTER_DOMAIN}

## Bitnami OAuth2 Proxy image
## ref: https://hub.docker.com/r/bitnami/redis/tags/
## @param image.registry OAuth2 Proxy image registry
## @param image.repository OAuth2 Proxy image repository
## @param image.tag OAuth2 Proxy image tag (immutable tags are recommended)
## @param image.digest OAuth2 Proxy image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
## @param image.pullPolicy OAuth2 Proxy image pull policy
## @param image.pullSecrets OAuth2 Proxy image pull secrets
##
image:
  registry: docker.io
  repository: bitnamilegacy/oauth2-proxy

## @section OAuth2 Proxy configuration parameters
##

## Configuration section
##
configuration:
  ## @param configuration.clientID OAuth client ID
  ##
  clientID: "oauth2-proxy"
  ## @param configuration.clientSecret OAuth client secret
  ##
  clientSecret: ""
  ## Create a new secret with the following command openssl rand -base64 32 | head -c 32 | base64
  ## Use an existing secret for OAuth2 credentials (see secret.yaml for required fields)
  ##
  ## @param configuration.cookieSecret OAuth cookie secret
  ##
  cookieSecret: ""
  ## @param configuration.existingSecret Secret with the client ID, secret and cookie secret
  ##
  existingSecret: "oauthproxy-client-secret"

  ## Custom configuration file: oauth2_proxy.cfg
  ## content: |
  ##   pass_basic_auth = false
  ##   pass_access_token = true
  ##
  ## @param configuration.content [string] Default configuration
  content: |
    email_domains = [ "*" ]
    upstreams = [ "http://oauth2-proxy-rel.oauth2-proxy.svc.cluster.local/oauth2/", "http://ollama-chart.default.svc.cluster.local/ollama/", "http://chatbot-api-chart.default.svc.cluster.local/v1/chats", "http://chatbot-api-chart.default.svc.cluster.local/v1/chats/", "http://agent-api-chart.default.svc.cluster.local/v1/assignments", "http://agent-api-chart.default.svc.cluster.local/v1/assignments/", "http://agent-api-chart.default.svc.cluster.local/v1/tools", "http://agent-api-chart.default.svc.cluster.local/v1/tools/", "http://memory-api-chart.default.svc.cluster.local/v1/memories", "http://memory-api-chart.default.svc.cluster.local/v1/memories/", "http://memory-distiller-chart.default.svc.cluster.local/v1/distill", "http://memory-distiller-chart.default.svc.cluster.local/v1/distill/", "http://admin-api-chart.default.svc.cluster.local/v1/admin", "http://admin-api-chart.default.svc.cluster.local/v1/admin/", "http://admin-api-chart.default.svc.cluster.local/v1/config", "http://admin-api-chart.default.svc.cluster.local/v1/config/", "http://portal-api-chart.default.svc.cluster.local/v1/portal", "http://portal-api-chart.default.svc.cluster.local/v1/portal/", "http://apidocs-api-chart.default.svc.cluster.local/v1/api-docs", "http://apidocs-api-chart.default.svc.cluster.local/v1/api-docs/" ]
    provider = "keycloak-oidc"
    provider_display_name = "Keycloak OIDC"
    oidc_issuer_url = "https://sso.${CLUSTER_DOMAIN}/realms/users"
    profile_url = "https://sso.${CLUSTER_DOMAIN}/realms/users/protocol/openid-connect/userinfo"
    validate_url = "https://sso.${CLUSTER_DOMAIN}/realms/users/protocol/openid-connect/userinfo"
    client_id = "oauth2-proxy"
    reverse_proxy = true
    cookie_name = "__secure-boucio"
    cookie_secure = true
    cookie_samesite = "none"
    cookie_httponly = true
    cookie_refresh = "120m"

    cookie_csrf_per_request = true
    cookie_csrf_expire = "120m"

    cookie_domains=[".${CLUSTER_DOMAIN}"] # Required so cookie can be read on all subdomains.
    whitelist_domains=[".${CLUSTER_DOMAIN}"] # Required to allow redirection back to original requested target.

    set_authorization_header = true
    skip_provider_button = true
    standard_logging = true
    scope="openid phone offline_access email web-origins microprofile-jwt profile address roles"
    auth_logging = true
    pass_access_token = true
    pass_authorization_header = true
    pass_user_headers = true
    pass_host_header = true
    request_logging = true
    session_store_type = "cookie"
    set_xauthrequest = true
    silence_ping_logging = true
    skip_auth_strip_headers = false
    skip_jwt_bearer_tokens = true
    ssl_insecure_skip_verify = true
    ssl_upstream_insecure_skip_verify = true

  ## @param configuration.oidcIssuerUrl OpenID Connect issuer URL
  oidcIssuerUrl: "https://sso.${CLUSTER_DOMAIN}/realms/users"

  ## @param configuration.redirectUrl OAuth Redirect URL
  #redirectUrl: "https://app.${CLUSTER_DOMAIN}/oauth2/callback"
  redirectUrl: ""

  ## @param configuration.whiteList Allowed domains for redirection after authentication. Prefix domain with a . or a *. to allow subdomains
  whiteList: ".${CLUSTER_DOMAIN}"

## Limits the number of pods of the replicated application that are down simultaneously from voluntary disruptions
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions
## e.g:
## podDisruptionBudget:
##   minAvailable: 1
##   maxUnavailable: 1
## @param pdb.create Enable a Pod Disruption Budget creation
## @param pdb.minAvailable Minimum number/percentage of pods that should remain scheduled
## @param pdb.maxUnavailable Maximum number/percentage of pods that may be made unavailable
##
pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ""

## @param hostAliases OAuth2 Proxy pods host aliases
## ref: https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []

## @param extraEnvVarsSecret Name of existing Secret containing extra env vars for OAuth2 Proxy nodes
##
extraEnvVarsSecret: "oauthproxy-client-secret"

redis:
  global:
    ## Security parameters
    ##
    security:
      allowInsecureImages: true # Required now since we move to Bitnami Legacy for now.
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: 7.4.3-debian-12-r0
